const filipinoBadWords = [
    'putangina',
    'gago',
    'ulol',
    'hayop',
    'tangina',
    'bobo',
    'tanga',
    'inutil',
    'hindot',
    'pakshet',
    'punyeta',
    'buwisit',
    'bwisit',
    'yawa',
    'sakim',
    'sutil',
    'bwiset',
    'kupal',
    'pakshet',
    'shunga',
    'demonyo',
    'bwisit',
    'burat',
    'puke',
    'pekpek',
    'susu',
    'kantot',
    'libog',
    'uyab',
    'kadyot',
    'pisting',
    'yot',
    'pota',
    'potek',
    'kupal',
    'lantod',
    'lantot',
    'amputa',
    'ampute',
    'ampota',
    'ampotah',
    'pisting yawa',
    'putragis',
    'putres',
    'tigas',
    'bastos',
    'bastusin',
    'mangmang',
    'tanginang',
    'hudas',
    'kupal',
    'lintik',
    'sutil',
    'tanga',
    'kain tae',
    'kain poop',
    'bwisit',
    'buraot',
    'hayup',
    'kamote',
    'leche',
    'tarantado',
    'kabayo',
    'tigas ng mukha',
    'tigas ng ulo',
    'hindi marunong umintindi',
    'epal',
    'mangmang',
    'ulol sa buwan',
    'gaga',
    'epal',
    'hangin',
    'kulang sa pansin',
    'patapon',
    'di marunong umintindi',
    'sinungaling',
    'mapagpanggap',
    'manggagago',
    'gaga',
    'hindot',
    'pokpok',
    'tukmol',
    'pucha',
    'sabaw',
    'sinungaling',
    'pangit',
    'tigas ng ulo',
    'walang hiya',
    'lalaking babae',
    'babae',
    'bayot',
    'jutay',
    'buang',
    'pango',
    'pakyu',
    'kupal',
    'inutil',
    'sipsip',
    'demonyo',
    'kampon ni satanas',
    'binabae',
    'tikbalang',
    'maniac',
    'mangkukulam',
    'manananggal',
    'berde',
    'bading',
    'bakla',
    'bayot',
    'buang',
    'giyawa',
    'hayop',
    'hudas',
    'kadyot',
    'kalbong buang',
    'kurakot',
    'lapastangan',
    'laptok',
    'libagon',
    'libak',
    'libog',
    'liguan',
    'limpyo',
    'lintian',

   
  ];
  
  export default filipinoBadWords;
  