export const ALL_PREVENTIVES_REQUEST = "ALL_PREVENTIVES_REQUEST";
export const ALL_PREVENTIVES_SUCCESS = "ALL_PREVENTIVES_SUCCESS";
export const ALL_PREVENTIVES_FAIL = "ALL_PREVENTIVES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const PREVENTIVE_DETAILS_REQUEST = "PREVENTIVE_DETAILS_REQUEST";
export const PREVENTIVE_DETAILS_SUCCESS = "PREVENTIVE_DETAILS_SUCCESS";
export const PREVENTIVE_DETAILS_FAIL = "PREVENTIVE_DETAILS_FAIL";

export const ADMIN_PREVENTIVES_REQUEST = "ADMIN_PREVENTIVES_REQUEST";
export const ADMIN_PREVENTIVES_SUCCESS = "ADMIN_PREVENTIVES_SUCCESS";
export const ADMIN_PREVENTIVES_FAIL = "ADMIN_PREVENTIVES_FAIL";

export const NEW_PREVENTIVE_REQUEST = "NEW_PREVENTIVE_REQUEST";
export const NEW_PREVENTIVE_SUCCESS = "NEW_PREVENTIVE_SUCCESS";
export const NEW_PREVENTIVE_RESET = "NEW_PREVENTIVE_RESET";
export const NEW_PREVENTIVE_FAIL = "NEW_PREVENTIVE_FAIL";

export const DELETE_PREVENTIVE_REQUEST = "DELETE_PREVENTIVE_REQUEST";
export const DELETE_PREVENTIVE_SUCCESS = "DELETE_PREVENTIVE_SUCCESS";
export const DELETE_PREVENTIVE_RESET = "DELETE_PREVENTIVE_RESET";
export const DELETE_PREVENTIVE_FAIL = "DELETE_PREVENTIVE_FAIL";

export const UPDATE_PREVENTIVE_REQUEST = "UPDATE_PREVENTIVE_REQUEST";
export const UPDATE_PREVENTIVE_SUCCESS = "UPDATE_PREVENTIVE_SUCCESS";
export const UPDATE_PREVENTIVE_RESET = "UPDATE_PREVENTIVE_RESET";
export const UPDATE_PREVENTIVE_FAIL = "UPDATE_PREVENTIVE_FAIL";