export const ALL_TAROS_REQUEST = "ALL_TAROS_REQUEST";
export const ALL_TAROS_SUCCESS = "ALL_TAROS_SUCCESS";
export const ALL_TAROS_FAIL = "ALL_TAROS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const TARO_DETAILS_REQUEST = "TARO_DETAILS_REQUEST";
export const TARO_DETAILS_SUCCESS = "TARO_DETAILS_SUCCESS";
export const TARO_DETAILS_FAIL = "TARO_DETAILS_FAIL";

export const ADMIN_TAROS_REQUEST = "ADMIN_TAROS_REQUEST";
export const ADMIN_TAROS_SUCCESS = "ADMIN_TAROS_SUCCESS";
export const ADMIN_TAROS_FAIL = "ADMIN_TAROS_FAIL";

export const NEW_TARO_REQUEST = "NEW_TARO_REQUEST";
export const NEW_TARO_SUCCESS = "NEW_TARO_SUCCESS";
export const NEW_TARO_RESET = "NEW_TARO_RESET";
export const NEW_TARO_FAIL = "NEW_TARO_FAIL";

export const DELETE_TARO_REQUEST = "DELETE_TARO_REQUEST";
export const DELETE_TARO_SUCCESS = "DELETE_TARO_SUCCESS";
export const DELETE_TARO_RESET = "DELETE_TARO_RESET";
export const DELETE_TARO_FAIL = "DELETE_TARO_FAIL";

export const UPDATE_TARO_REQUEST = "UPDATE_TARO_REQUEST";
export const UPDATE_TARO_SUCCESS = "UPDATE_TARO_SUCCESS";
export const UPDATE_TARO_RESET = "UPDATE_TARO_RESET";
export const UPDATE_TARO_FAIL = "UPDATE_TARO_FAIL";